

    
version: '3.0'

services:
  node-app:
    #container_name: myapp2
    build: .
    image: redasaad123/docker-test
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 2
        delay: 10s

    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - mongo-DB:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      #ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  redis:
    image: redis
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app




volumes:
  mongo-DB:


  

